# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [4]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [5]:
# Create a 1-dimensional NumPy array using np.array()
num_arr = np.array([1, 2, 3, 4, 5])
print("1-dimensional array","\n", num_arr, "\n")

# Create a 2-dimensional NumPy array using np.array()
num_arr_2d = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("2-dimensional array","\n", num_arr_2d, "\n")

# Create a 3-dimensional Numpy array using np.array()
num_arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print("3-dimensional array", "\n", num_arr_3d, "\n")


1-dimensional array 
 [1 2 3 4 5] 

2-dimensional array 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

3-dimensional array 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]] 



Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [6]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("________________________________ Array shape _______________________________", '\n')
print("1-d array shape", "\n", num_arr.shape, "\n")
print("2-d array shape", "\n", num_arr_2d.shape, "\n")
print("2-d array shape", "\n", num_arr_3d.shape, "\n")

print("_____________________________ Number of dimension ________________________", '\n')
print("1-d array dimensions", "\n", num_arr.ndim, "\n")
print("2-d array dimensions", "\n", num_arr_2d.ndim, "\n")
print("3-d array dimensions", "\n", num_arr_3d.ndim, "\n")

print("_____________________________ Data types __________________________________", '\n')
print("1-d array data type", "\n", num_arr.dtype, "\n")
print("2-d array data type", "\n", num_arr_2d.dtype, "\n")
print("3-d array data type", "\n", num_arr_3d.dtype, "\n")

print("_____________________________ Size __________________________________", '\n')
print("1-d array size", "\n", num_arr.size, "\n")
print("2-d array size", "\n", num_arr_2d.size, "\n")
print("3-d array size", "\n", num_arr_3d.size, "\n")

print("_____________________________ Type __________________________________", '\n')
print("1-d array type", "\n", type(num_arr), "\n")
print("2-d array type", "\n", type(num_arr_2d), "\n")
print("3-d array type", "\n", type(num_arr_3d), "\n")

________________________________ Array shape _______________________________ 

1-d array shape 
 (5,) 

2-d array shape 
 (2, 5) 

2-d array shape 
 (1, 3, 3) 

_____________________________ Number of dimension ________________________ 

1-d array dimensions 
 1 

2-d array dimensions 
 2 

3-d array dimensions 
 3 

_____________________________ Data types __________________________________ 

1-d array data type 
 int64 

2-d array data type 
 int64 

3-d array data type 
 int64 

_____________________________ Size __________________________________ 

1-d array size 
 5 

2-d array size 
 10 

3-d array size 
 9 

_____________________________ Type __________________________________ 

1-d array type 
 <class 'numpy.ndarray'> 

2-d array type 
 <class 'numpy.ndarray'> 

3-d array type 
 <class 'numpy.ndarray'> 



In [7]:
# Attributes of 2-dimensional array

In [8]:
# Attributes of 3-dimensional array

In [57]:
# Import pandas and create a DataFrame out of one of the arrays you've created
import pandas as pd 
 
data_frame = pd.DataFrame(num_arr_2d)
print(data_frame)

   0  1  2  3   4
0  1  2  3  4   5
1  6  7  8  9  10


In [60]:
# Create an array of shape (10, 2) with only ones
ones_arr = np.ones((10, 2))
print(ones_arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [64]:
# Create an array of shape (7, 2, 3) of only zeros
zeros_arr = np.zeros((2, 2, 3, 2))
print(zeros_arr)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]]]]


In [65]:
# Create an array within a range of 0 and 100 with step 3
range_arr = np.arange(0, 100, 3)
print(range_arr)


[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69
 72 75 78 81 84 87 90 93 96 99]


In [66]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_arr = np.random.randint(10, size=(7, 2))
print(random_arr)

[[0 4]
 [5 6]
 [3 2]
 [7 4]
 [2 9]
 [5 6]
 [4 3]]


In [71]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_floar_arr = np.random.random((3,5))
print(random_floar_arr)

[[0.10534108 0.16026196 0.84068848 0.82808289 0.63230526]
 [0.5104438  0.87317576 0.39013352 0.77999197 0.02654409]
 [0.31951884 0.59019346 0.77370361 0.16033374 0.52516082]]


In [121]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_arr2 = np.random.randint(low=0,high=100, size=(4, 6))
print(random_arr2)

[[51 92 14 71 60 20]
 [82 86 74 74 87 99]
 [23  2 21 52  1 87]
 [29 37  1 63 59 20]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [125]:
# Create an array of random numbers between 1 & 10 of size (3, 7) and save it to a variable
random_element_arr = np.random.randint(low = 1 , high = 10, size=(3, 7))
print(random_element_arr)

# Find the unique numbers in the array you just created
unique_element = np.unique(random_element_arr)
print("Unique element", unique_element)

[[5 7 9 7 9 8 2]
 [1 7 7 8 5 3 8]
 [6 3 1 3 5 3 1]]
Unique element [1 2 3 5 6 7 8 9]


In [126]:
# Find the 0'th index of the latest array you created
print(unique_element[0])

1


In [132]:
# Get the first 2 rows of latest array you created
print(random_element_arr[:2])

[[5 7 9 7 9 8 2]
 [1 7 7 8 5 3 8]]


In [133]:
# Get the first 2 values of the first 2 rows of the latest array
print(random_element_arr[:2, :2])

[[5 7]
 [1 7]]


In [148]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
random_arr_one = np.random.randint(low  = 0, high = 10, size = (3, 5))
print(random_arr_one)

random_arr_two = np.random.randint(low=0, high=10, size=(3, 5))
print(random_arr_two)

[[8 0 7 6 1]
 [7 0 8 8 1]
 [6 9 2 6 9]]
[[8 3 0 1 0]
 [4 4 6 8 8]
 [2 2 2 3 7]]


In [150]:
# Add the two arrays together
sum_of_two_arr = np.add(random_arr_one, random_arr_two)
print(sum_of_two_arr)

[[16  3  7  7  1]
 [11  4 14 16  9]
 [ 8 11  4  9 16]]


In [151]:
# Create another array of ones of shape (5, 3)
ones_shpae_arr = np.ones((3, 5))
print(ones_shpae_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [152]:
# Try add the array of ones and the other most recent array together
add_most_recent_arr = np.add(ones_shpae_arr, sum_of_two_arr)
print(add_most_recent_arr)

[[17.  4.  8.  8.  2.]
 [12.  5. 15. 17. 10.]
 [ 9. 12.  5. 10. 17.]]


When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [154]:
# Create another array of ones of shape (3, 5)
one_shape_second_arr = np.ones((3, 5))
print(one_shape_second_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [155]:
# Subtract the new array of ones from the other most recent array
subtract_of_new_arr = np.subtract(add_most_recent_arr, one_shape_second_arr)
print(subtract_of_new_arr)

[[16.  3.  7.  7.  1.]
 [11.  4. 14. 16.  9.]
 [ 8. 11.  4.  9. 16.]]


In [156]:
# Multiply the ones array with the latest array
mul_of_latest_arr = np.multiply(one_shape_second_arr, subtract_of_new_arr)
print(mul_of_latest_arr)

[[16.  3.  7.  7.  1.]
 [11.  4. 14. 16.  9.]
 [ 8. 11.  4.  9. 16.]]


In [157]:
# Take the latest array to the power of 2 using '**'
power_of_two = mul_of_latest_arr ** 2
power_of_two

array([[256.,   9.,  49.,  49.,   1.],
       [121.,  16., 196., 256.,  81.],
       [ 64., 121.,  16.,  81., 256.]])

In [158]:
# Do the same thing with np.square()
power_of_arr = np.square(mul_of_latest_arr)
power_of_arr


array([[256.,   9.,  49.,  49.,   1.],
       [121.,  16., 196., 256.,  81.],
       [ 64., 121.,  16.,  81., 256.]])

In [159]:
# Find the mean of the latest array using np.mean()
mean_of_latest_arr = np.mean(power_of_arr)
mean_of_latest_arr

104.8

In [160]:
# Find the maximum of the latest array using np.max()
max_of_latest_arr = np.max(power_of_arr)
max_of_latest_arr

256.0

In [161]:
# Find the minimum of the latest array using np.min()
min_of_latest_arr = np.min(power_of_arr)
min_of_latest_arr

1.0

In [162]:
# Find the standard deviation of the latest array
std_deviation = np.std(power_of_arr)
std_deviation

90.24943213117743

In [163]:
# Find the variance of the latest array
variance_of_arr = np.var(power_of_arr)
variance_of_arr


8144.96

In [164]:
# Reshape the latest array to (3, 5, 1)
newshape_arr = np.reshape(power_of_arr, (3, 5, 1))
newshape_arr

array([[[256.],
        [  9.],
        [ 49.],
        [ 49.],
        [  1.]],

       [[121.],
        [ 16.],
        [196.],
        [256.],
        [ 81.]],

       [[ 64.],
        [121.],
        [ 16.],
        [ 81.],
        [256.]]])

In [165]:
# Transpose the latest array
transpose_of_newshape = newshape_arr.T
transpose_of_newshape


array([[[256., 121.,  64.],
        [  9.,  16., 121.],
        [ 49., 196.,  16.],
        [ 49., 256.,  81.],
        [  1.,  81., 256.]]])

What does the transpose do?

In [170]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
random_int_arr = np.random.random(size=(3, 3))

random_int_arr_two = np.random.random(size=(3, 2))
random_int_arr , random_int_arr_two

(array([[0.76855401, 0.04360377, 0.99455051],
        [0.46994451, 0.27956034, 0.88349402],
        [0.74771877, 0.95307185, 0.3307503 ]]),
 array([[0.55276497, 0.57229247],
        [0.98033158, 0.07534626],
        [0.30569702, 0.19091103]]))

In [172]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(random_int_arr, random_int_arr_two)
dot_product , dot_product.shape

(array([[0.77160702, 0.63299372],
        [0.80391219, 0.45867829],
        [1.44874856, 0.5628681 ]]),
 (3, 2))

In [174]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
random_int_array = np.random.random(size=(4, 3))

random_int_array_two = np.random.random(size=(4, 3))
random_int_array , random_int_array_two

(array([[0.26847486, 0.48527987, 0.37268687],
        [0.39469147, 0.84421314, 0.93001683],
        [0.07041613, 0.20891872, 0.67114352],
        [0.35864678, 0.25416365, 0.29529059]]),
 array([[0.32255076, 0.84866979, 0.13662133],
        [0.708911  , 0.55281998, 0.29651014],
        [0.41978086, 0.25620694, 0.61151371],
        [0.08159418, 0.00518486, 0.62789441]]))

In [176]:
# Perform a dot product on the two newest arrays you created
dot_product_two = np.dot(random_int_array, random_int_array_two.T)
dot_product_two

array([[0.54935612, 0.56910262, 0.46493581, 0.2584301 ],
       [0.97082637, 1.02225844, 0.95069524, 0.62053403],
       [0.2917083 , 0.36441407, 0.49349923, 0.42823603],
       [0.3717258 , 0.48231204, 0.39624579, 0.21599261]])

It doesn't work. How would you fix it?

In [40]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [178]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
random_int_array = np.random.randint(10, size=(4, 3))

random_int_array_two = np.random.randint(10, size=(4, 3))
random_int_array , random_int_array_two

(array([[3, 0, 7],
        [2, 6, 1],
        [1, 6, 5],
        [2, 8, 9]]),
 array([[5, 9, 9],
        [5, 0, 3],
        [9, 5, 5],
        [4, 0, 7]]))

In [179]:
# Compare the two arrays with '>'
random_int_array > random_int_array_two

array([[False, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

In [181]:
# Compare the two arrays with '>='
random_int_array >= random_int_array_two

array([6, 6, 5, 8, 9])

In [186]:
# Find which elements of the first array are greater than 7
# element_gt_7 = np.argwhere(random_int_array > 7)
# element_gt_7
random_int_array[random_int_array > 7]

array([8, 9])

In [187]:
# Which parts of each array are equal? (try using '==')
random_int_array[random_int_array == random_int_array_two]


array([5])

In [199]:
# Sort one of the arrays you just created in ascending order
random_int_array_two.sort()
random_int_array_two

array([[5, 9, 9],
       [0, 3, 5],
       [5, 5, 9],
       [0, 4, 7]])

In [198]:
# Sort the indexes of one of the arrays you just created
# np.argsort(random_int_array_two)

In [205]:
# Find the index with the maximum value in one of the arrays you've created
max_index = np.argmax(random_int_array_two)
max_index,random_int_arr_two[max_index],random_int_arr_two

(1,
 array([0.98033158, 0.07534626]),
 array([[0.55276497, 0.57229247],
        [0.98033158, 0.07534626],
        [0.30569702, 0.19091103]]))

In [207]:
# Find the index with the minimum value in one of the arrays you've created
min_index = np.argmin(random_int_array_two)
min_index


3

In [208]:
# Find the indexes with the maximum values down the 1st axis (axis=1) of one of the arrays you created
np.argmax(random_int_arr_two, axis=1)

array([1, 0, 0])

In [209]:
# Find the indexes with the minimum values across the 0th axis (axis=0) of one of the arrays you created
np.argmax(random_int_arr_two, axis=0)

array([1, 0])

In [212]:
# Create an array of normally distributed random numbers
normal_array  = np.random.random(size=5)
normal_array

array([0.54063512, 0.6374299 , 0.72609133, 0.97585208, 0.51630035])

In [213]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.